task
DmitriiParshin/task_1 pull request #3
Opened 2022-12-27 11:04 UTC by DmitriiParshin

2022-12-27 12:21 UTC, ilyachch requested changes

2022-12-27 12:21 UTC, ilyachch commented on .gitignore
> +db.sqlite3
а `.pyc`, `__pycache__`, `.venv`, etc?

2022-12-27 12:21 UTC, ilyachch commented on backend/quiz/models.py
> +        default=uuid.uuid4().hex,
UUIDField принимает тип uuid. плюс после каждого запуска у тебя будет одинаковый UUID при создании Theme. Почитай, как работает default в моделях Django. (подсказка - это работает, как callback)

2022-12-27 12:21 UTC, ilyachch commented on backend/quiz/models.py
> +    name = models.CharField(max_length=256, db_index=True)
зачем тут `db_index=True`?

2022-12-27 12:21 UTC, ilyachch commented on backend/quiz/models.py
> +        default=uuid.uuid4().hex,
> UUIDField принимает тип uuid. плюс после каждого запуска у тебя будет одинаковый UUID при создании Theme. Почитай, как работает default в моделях Django. (подсказка - это работает, как callback)

2022-12-27 12:21 UTC, ilyachch commented on backend/quiz/models.py
> +    name = models.CharField(max_length=256, db_index=True)
> зачем тут db_index=True?

2022-12-27 12:21 UTC, ilyachch commented on backend/quiz/models.py
> +        Theme,
при указании FK - лучше оборачивать в скобки. Django найдет модель, которую ты указал, но зато это избавит от потенциальных проблем порядка определения классов и циклических импортов

2022-12-27 12:21 UTC, ilyachch commented on backend/quiz/models.py
> +    number = models.UUIDField(
Я не увеерен, что тут это поле вообще нужно. И тем более, индекс на нем - FK создается всегда с индексом, а оперировать вопросами без темы в большинстве случаев не придется.

2022-12-27 12:21 UTC, ilyachch commented on backend/quiz/models.py
> +    wrong_answer = models.CharField(max_length=256)
а почему не сделать через одно поле "текст ответа" и отметку "ответ правильный"?

2022-12-27 12:21 UTC, ilyachch commented on backend/quiz/models.py
> +class Question(models.Model):
Как ты будешь определять, какой виджет отрисовывать для вопроса?

2022-12-27 12:21 UTC, ilyachch commented on backend/quiz/models.py
> +        blank=True,
почему?

2022-12-27 12:21 UTC, ilyachch commented on backend/quiz/models.py
> +        null=True,
почему?

2022-12-27 12:21 UTC, ilyachch commented on backend/quiz/models.py
> +class TestResult(models.Model):
а вот тут UUID прям просится. Пользователь по сути будет взаимодействовать в основном с этим обънектом

2022-12-27 12:21 UTC, ilyachch commented on backend/quiz/models.py
> +        related_name="results"
related_name идентичное related_name другой модели - плохая практика

2022-12-27 12:28 UTC, ilyachch commented
Так же вопросы:
1) Почему pytest в основных зависимостях? Ты планируешь в продакшене гонять тесты?
2) Почему нет миграций?
3) зачем в `pyproject.toml` `packages = [{include = "task_1"}]`?
4) если в `pyproject.toml` указана `license = "MIT"`, то где текст самой лицензии?
5) файл `backend/auth/groups/__init__.py` остался. Зачем?

2022-12-27 13:13 UTC, DmitriiParshin commented on backend/quiz/models.py
> +        default=uuid.uuid4().hex,
точно, видел же пример, я просто не понял, как сделать что бы number был без дефисов

2022-12-27 13:17 UTC, DmitriiParshin commented on backend/quiz/models.py
> +    name = models.CharField(max_length=256, db_index=True)
думал что поиск по name в Theme будет актуальнее

2022-12-27 13:25 UTC, DmitriiParshin commented on backend/quiz/models.py
> +        Theme,
Я правтльно понимаю, что необходимо обернуть название модели, на которую ссылается ФК? - (Theme,),

2022-12-27 14:48 UTC, DmitriiParshin commented on backend/quiz/models.py
> +    wrong_answer = models.CharField(max_length=256)
не могу сообразить, как в чарфилде сделать отметку правильного ответа?

2022-12-27 19:22 UTC, ilyachch commented on backend/quiz/models.py
> +    wrong_answer = models.CharField(max_length=256)
потому, что тебе нужен не чарфилд

2022-12-28 10:04 UTC, ilyachch commented on backend/quiz/models.py
> +        Theme,
обознался. в кавычки - `'Theme'`

2022-12-28 10:08 UTC, ilyachch commented on backend/quiz/models.py
> +    name = models.CharField(max_length=256, db_index=True)
поиск в Django не самая простая вещь. если делать через `contains` или `icontains` - не особо юзабелен (плохое качество поиска по произвольной подстроке + плохая производительность). правильнее использовать нечеткий поиск, а это целый новый мир со своими подводными камнями

2022-12-28 10:08 UTC, ilyachch commented on backend/quiz/models.py
> +        default=uuid.uuid4().hex,
причем тут дефисы?

2022-12-28 10:10 UTC, ilyachch commented on LICENSE
> +MIT License
> если в pyproject.toml указана license = "MIT", то где текст самой лицензии?

так же правильным решением было бы удалить строку с лицензией из `pyproject.toml`

2022-12-28 10:10 UTC, ilyachch commented
в код попал `backend/db.sqlite3`

2022-12-28 10:28 UTC, ilyachch requested changes

2022-12-28 10:28 UTC, ilyachch commented on backend/quiz/admin.py
> +from quiz.models import Theme, Question, PossibleAnswer, ResultTest, UserAnswer
поторопился. правильнее было бы сделать все подмодели через Inline

2022-12-28 10:28 UTC, ilyachch commented on backend/quiz/apps.py
> +    DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
чем тебя не устроило предыдущее написание?

2022-12-28 10:28 UTC, ilyachch commented on backend/quiz/migrations/0001_initial.py
> +# Generated by Django 4.1.4 on 2022-12-27 12:05
очень правильным решением было бы исключить миграции из проверок и правок black и isort. линтеры и форматтеры должны работать исключительно с тем, что написано руками. любой генерируемый код должн быть исключен

2022-12-28 10:28 UTC, ilyachch commented on backend/quiz/migrations/0003_theme_slug.py
> +# Generated by Django 4.1.4 on 2022-12-28 09:34
создание нескольких миграций в процессе разработки - хорошо.
однако, очень удобно перед окончательным мержем - удалить их все и пересоздать, чтобы на каждое приложение в PR было наименьшее количество миграций (не обязательно это 1 - в некоторых случах нужны data-миграции)

2022-12-28 10:28 UTC, ilyachch commented on backend/quiz/models.py
> +    TYPES_ANSWER = [
для подобного есть [Enumeration types](https://docs.djangoproject.com/en/4.1/ref/models/fields/#enumeration-types)

2022-12-28 10:28 UTC, ilyachch commented on backend/quiz/models.py
> +    type_answer = models.CharField(max_length=32, choices=TYPES_ANSWER)
1) это не тип ответа, а тип вопроса
2) `Type answer` - выглядит как указание, "вбей ответ". Правильнее поменять слова местами. `Answer type`

2022-12-28 10:28 UTC, ilyachch commented on backend/quiz/models.py
> +class PossibleAnswer(models.Model):
в итоге у тебя нет возможности определить, какой ответ правильный. Изучи, какие есть типы полей (FK и CharField - далеко не все варианты)

2022-12-28 10:28 UTC, ilyachch commented on backend/quiz/urls.py
> +from django.urls import path
опять же, торопишься. Пока модели данных нет - за остальное браться смысла нет. Модели - основа всего. после их изменения, возможно, придется переделывать url-ы и view

2022-12-28 10:28 UTC, ilyachch commented on backend/quiz/views.py
> +from quiz.models import Theme, Question
> опять же, торопишься. Пока модели данных нет - за остальное браться смысла нет. Модели - основа всего. после их изменения, возможно, придется переделывать url-ы и view

2022-12-28 10:28 UTC, ilyachch commented on backend/settings/settings.py
> +    "quiz.apps.QuizConfig",
на самом деле, не принципиально

2022-12-28 10:28 UTC, ilyachch commented on backend/settings/settings.py
> +TEMPLATES_DIR = BASE_DIR / "templates"
вообще, это вкусовщина. но намного удобнее, если каждое приложение содержит в себе свои шаблоны.
достаточно часто вижу, как создается приложение Core, где и есть точка входа (пока не надо делать)

2022-12-28 11:36 UTC, DmitriiParshin commented on backend/quiz/apps.py
> +    DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
))) искал баг

2022-12-29 13:09 UTC, DmitriiParshin commented on backend/quiz/models.py
> +        User,
Эту конструкцию "User = get_user_model()" порекомендовали использовать на курсе, т.к. обращаться напрямую к модели User неправильно(небезопасно, точно не помню).

2022-12-29 14:27 UTC, ilyachch approved these changes

2022-12-29 14:42 UTC, merged